// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol ArkanaKeysGlobalProtocol {
    var hostname: String { get }
    var authorName: String { get }
    var siteName: String { get }
    var mastodonPage: String { get }
    var mastodonHandle: String { get }
}

public protocol ArkanaKeysEnvironmentProtocol {
}
