# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
repository:          igorcferreira/DevelopmentBlog
title:               Igor Ferreira
tagline:             'A simple blog, about my technical discoveries along the way'
description:         'A simple blog, about my technical discoveries along the way. Here, I\'ll mostly post things about Swift, iOS, and some other random dev tools'
url:                 https://igorcferreira.dev
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Igor Ferreira
  url:               https://twitter.com/icastanheda
  email:             igorcferreira@hotmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate, jekyll-github-metadata]

github:
  repo:           https://github.com/igorcferreira/DevelopmentBlog
