# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
repository:          igorcferreira/DevelopmentBlog
title:               site.title
tagline:             site.tagline
description:         site.description
url:                 https://igorcferreira.dev
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Igor Ferreira
  url:               https://twitter.com/icastanheda
  twitter:           icastanheda
  picture:           /public/user_avatar.png

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages: ["en", "pt"]
defaultLang: en
exclude_from_localizations: ["javascript", "images", "public"]
languageNames:
  pt: Português
  en: English

feed:
  path: atom.xml
  excerpt_only: true

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'static.json', 'README.md', 'CONTRIBUTING.md', 'LICENSE.md']

github:
  repo: https://github.com/igorcferreira/DevelopmentBlog
