name: Deploy Static files

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        name: Install dependencies
        with:
          bundler-cache: true
      - name: Build Static files
        run: |
          bundle exec jekyll build
      - name: Checkout Static branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false
      - name: Clean folder
        run: |
          find . -not -name '_site' -not -name '.git' -not -name '.gitignore' -not -name '.' -not -name '..' -maxdepth 1 -exec rm -r "{}" \;
      - name: Move files
        run: |
          cp -r _site/. .
      - name: Remove _site folder
        run: |
          rm -r _site
      - name: Commit changes
        run: |
          git add . && git commit -m "Publish new version"
      - name: Push changes
        run: |
          git push origin gh-pages
