name: Deploy Static files

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v2
      - name: Remove lock to avoid Mac issues
        run: |
          rm Gemfile.lock
      - uses: ruby/setup-ruby@v1
        name: Install dependencies
        with:
          bundler-cache: true
      - name: Build Static files
        run: |
          bundle exec jekyll build
      - name: Checkout Static branch
        run: |
          git fetch --all --prune
          git checkout gh-pages
      - name: Clean folder
        run: |
          rm -v !(_site)
      - name: Move files
        run: |
          cp -r _site .
      - name: Remove _site folder
        run: |
          rm -r _site
      - name: Commit changes
        run: |
          git add . && git commit -m "Publish new version"
      - name: Push changes
        run: |
          git push origin gh-pages
